[package]
name = "normal-map-generator-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["sakikuroe"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
